"""Cloud provider-specific logging configuration classes."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/configs/cloud.ipynb.

# %% auto 0
__all__ = []

# %% ../../nbs/configs/cloud.ipynb 2
from ..client.base import OutputMode, LogLevel, ServiceConfig

from ..client.exceptions import LogConfigError

# %% ../../nbs/configs/cloud.ipynb 3
import os
from typing import Optional, Dict, Any
from dataclasses import dataclass, field
from abc import abstractmethod
