"""Console-specific log configuration class."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/configs/console.ipynb.

# %% auto 0
__all__ = ['Console_ServiceConfig']

# %% ../../nbs/configs/console.ipynb 2
from dc_logger.client.base import ServiceConfig, OutputMode
from dataclasses import dataclass

# %% ../../nbs/configs/console.ipynb 3
@dataclass
class Console_ServiceConfig(ServiceConfig):
    """Console-specific log configuration"""
    
    output_mode: OutputMode = "console"

    def validate_config(self) -> bool:
        return True
