# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/services/base.ipynb.

# %% auto 0
__all__ = ['CloudHandler']

# %% ../../nbs/services/base.ipynb 2
from ..client.base import LogEntry
from ..client.exceptions import LogWriteError

# %% ../../nbs/services/base.ipynb 3
from dc_logger.client.base import ServiceHandler

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import List

# %% ../../nbs/services/base.ipynb 4
@dataclass
class CloudHandler(ServiceHandler):
    """Base class for cloud log handlers"""

    # def __init__(self, config):
    #     super().__init__(config)
    #     self.cloud_config = config.to_platform_config()
    #     config.validate_config()

    

