"""Logging-specific exceptions for the library."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/client/exceptions.ipynb.

# %% auto 0
__all__ = ['DC_LoggingError', 'LogHandlerError', 'LogConfigError', 'LogWriteError', 'LogFlushError']

# %% ../../nbs/client/exceptions.ipynb 2
class DC_LoggingError(Exception):
    """Base exception for logging errors"""
    pass

class LogHandlerError(DC_LoggingError):
    """Exception for log handler errors"""
    pass

class LogConfigError(DC_LoggingError):
    """Exception for log configuration errors"""
    pass

class LogWriteError(DC_LoggingError):
    """Exception for log write errors"""
    pass

class LogFlushError(DC_LoggingError):
    """Exception for log flush errors"""
    pass
