# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/services/console/console.ipynb.

# %% auto 0
__all__ = []

# %% ../../../nbs/services/console/console.ipynb 1
import json
from typing import List

from dc_logger.client.base import ServiceHandler, ServiceConfig, LogEntry

